name: on-push
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn lint
  test:
    runs-on: ubuntu-latest
    steps:
    - run: yarn install
    - run: yarn test

